// Thomas Stratfold - 1192953
import java.io.*;
import java.util.Scanner;

public class FreqAnalInitDriver {
	public static void main(String[] args) {
		String[] Names = {"Abkhaz", "Achehnese", "Achuar Shiwiar", "Afaan Oromo", "Afrikaans", "Aguaruna", "Albanian","All_FAI", 
		"Altay", 
		"Amahuaca", 
		"Amarakaeri", 
		"Amuesha Yanesha", 
		"Ao", 
		"Arabela", 
		"Arabic", 
		"Ashaninca", 
		"Asheninca", 
		"Asturian", 
		"Aymara", 
		"Bahasa Indonesia", 
		"Bahasa Melayu", 
		"Balinese", 
		"Basque", 
		"Belorus", 
		"Bemba", 
		"Beti", 
		"Bichelamar", 
		"Bikol", 
		"Bora", 
		"Bosnian", 
		"Breton", 
		"Bugisnese", 
		"Bulgarian", 
		"Cakchiquel", 
		"Campa Pajonalino", 
		"Candoshi Shapra", 
		"Caquinte", 
		"Cashibo Cacataibo", 
		"Cashinahua", 
		"Catalan", 
		"Cebuano", 
		"Chamorro", 
		"Changane", 
		"Chayahuita", 
		"Chechewa", 
		"Chickasaw", 
		"Chin Falam", 
		"Chin Hakha", 
		"Chin Matu", 
		"Chin Tiddim", 
		"Chinanteco Ajitlan", 
		"Chinanteco", 
		"Chuuk", 
		"Cokwe", 
		"Corsican", 
		"Creole Kreyol", 
		"Creole Popular", 
		"Crioulo", 
		"Cyrmaeg", 
		"Czech", 
		"Dagaare", 
		"Danish", 
		"Diola Jola Fogny", 
		"Dutch", 
		"Edo", 
		"Efik", 
		"ENGadvertiser_FAI", 
		"English", 
		"Esperanto", 
		"Estonian", 
		"Evenki", 
		"Faroese", 
		"Fijian", 
		"Filipino", 
		"Finnish", 
		"Fiote", 
		"Forro", 
		"Frisian", 
		"Friulian", 
		"Gaelic I", 
		"Gaelic S", 
		"Gagauz", 
		"Galician", 
		"Garifuna", 
		"German", 
		"Greek", 
		"Greenlandic", 
		"Guarani", 
		"Guarayo", 
		"Hani", 
		"Hausa", 
		"Hawaiian", 
		"Hiligaynon", 
		"Hmong NEG", 
		"Hmong SEG", 
		"Hmong SGY", 
		"Huasteco", 
		"Huitoto Murui", 
		"Hungarian", 
		"Icelandic", 
		"Ido", 
		"Igbo", 
		"Ilocano", 
		"Interlingua", 
		"Italian", 
		"Javanese", 
		"Kanuri Yerwa", 
		"Kaonde", 
		"Kapampangan", 
		"Karelian", 
		"Kazakh", 
		"Khasi", 
		"Kibushi", 
		"Kiche", 
		"Kikongo ya letat", 
		"Kimbundu", 
		"Kinyamwezi", 
		"Kinyarwanda", 
		"Kishi", 
		"Komi Permian", 
		"Korean", 
		"Kurdish", 
		"Kurmanji", 
		"Kyrgyz", 
		"Ladino", 
		"Latin 1", 
		"Latin 2", 
		"Latvian", 
		"Lingala", 
		"Lithuanian", 
		"Low German", 
		"Lozi", 
		"Luba Kasai", 

"Luganda","Lunda","Luva", 
"Luxembourgish", 
"Macedonian", 
"Madurese", 
"Makonde", 
"Malagasy", 
"Maltese", 
"Mam", 
"Maori CI", 
"Maori", 
"Mapudungun", 
"Marshallese", 
"Matses", 
"Mauka", 
"Mayan", 
"Mazateco", 
"Minangkabau", 
"Miskito", 
"Mizo", 
"Moore", 
"Mozarabic", 
"Nahuatl", 
"Nanai", 
"Ndebele", 
"Nganasan", 
"Ngangela", 
"Nigerian Pidgin English", 
"Nomatsiguenga", 
"Northern Sotho", 
"Norwegian", 
"Nyanja", 
"Occitan Auvergnat", 
"Occitan Languedocien", 
"Osetin", 
"Oshiwambo", 
"Paez", 
"Palauan", 
"Peuhl", 
"Picard", 
"Pijin", 
"Pipil", 
"Polish", 
"Ponapean", 
"Portuguese", 
"Provencau", 
"Pulaar", 
"Qechi", 
"Quechua dA", 
"Quechua dAP", 
"Quechua dC", 
"Quechua dCH", 
"Quechua dCot", 
"Quechua dCusco", 
"Quechua dH", 
"Quechua dM", 
"Quechua dNdJ", 
"Quechua dP", 
"Quechua", 
"Quichua", 
"Rhaeto Romance", 
"Romanian", 
"Romany", 
"Rukonzo", 
"Rundi", 
"Runyankore rukiga", 
"Russian", 
"Sami", 
"Sammarinese", 
"Samoan", 
"Sango", 
"Sardinian", 
"Scots", 
"Seereer", 
"Serbian",  
"Seselwa Creole French", 
"Sharanahua", 
"Shimaore", 
"Shipibo Conibo", 
"Shona", 
"Siswati", 
"Slovak", 
"Slovenian", 
"Somali", 
"Soninke", 
"Sorbian", 
"Sotho", 
"Spanish", 
"Sudanese", 
"Swahili", 
"Swedish", 
"Tahitian", 
"Tajik", 
"Tamazight", 
"Tenek", 
"Tetum", 
"Tiv", 
"Toba", 
"Tojol", 
"Tok Pisin", 
"Tonga", 
"Tongan", 
"Totonaco", 
"Tshivenda", 
"Tswana", 
"Turkish", 
"Tzeltal", 
"Tzotzil", 
"Uilta", 
"Ukranian", 
"Umbundu", 
"Urarina", 
"Uzbek", 
"Veps", 
"Vlach", 
"Walloon", 
"Waray", 
"Wayuu", 
"Wolof", 
"Xhosa", 
"Yagua", 
"Yanomamo", 
"Yao", 
"Yapese", 
"Yoruba", 
"Zapoteco SLQ", 
"Zapoteco", 
"Zhuang", 
"Zulu"};
		//Commented out rest of list		
		/*,"Alsatian","Anglo-Saxon","Aragonese","Aromanian","Asturian",
		"Azeri","Basque","Belarian_T","Bislama","Bosinian","Breton","Bunduliwan","Catalan","Cebuano",
		"Cecarakan_T","Cheyenne","Cornish","Cujoltha_T","Cymraeg","Dakota","Dutch","Esperanto",
		"Estonian","Fiji_Hindi","Finnish","Folkspraak","French","German","Greenlandic","Haitian","Hausa",
		"Hawaiian","Hungarian","Ido","Ilocano","Indonesian","Interglossa","Interlingua","Irish","Kam",
		"Kirundi","Klingon","Korean_T","Latin","Lingala","Lingua Franca Nova","Low_Saxon","Malagasy",
		"Maltese","Manx_Gaelic","Maori","Massachusett","Melayu","Ndebele","Norwegian","Nsotho",
		"Ojibwe","Paite","Papiamentu","Sami North","Sami South","Samoan","Scottish_Gaelic","Sesotho",
		"Shona","Somali","Sranan_Tongo","Swahili","Tagalog","Tamasheq","Thai_T","Toki Pona","Tsonga",
		"Tswana","Turkish","Uab_Meto","Viozian","White_Hmong","Wolof","Xhosa","Zarma","Zulu","English",
		"Danish"};*/
		FreqAnalInit FAI = new FreqAnalInit();
		BufferedReader file = null;
		int[] array = null;
		try{
		FileOutputStream FOS = new FileOutputStream("All_FAI.txt");
		ObjectOutputStream OOS = new ObjectOutputStream(FOS);
		//OOS.writeObject("                                   Frequency Analysis of Initial Letters For All Languages\n");		
		OOS.writeObject(" Blah\n");
		for(int i=0; i <Names.length; i++) {
				file = FAI.ReadFile(Names[i]);
				array = FAI.FreqAnal(file);
				OOS.writeObject("                           "+Names[i]+"\n"); //THIS IS ORIGINAL
				//System.out.println("                           "+Names[i]+"\n"); //THIS IS MODIFIED TO OUTPUT LANGUAGE NAMES IN TERMINAL
				for(int j = 0; j <26; j++) {
					int alpha = 'A'+j;
					OOS.writeObject(" "+(char)alpha+": "+array[j]+"\n"); //THIS IS ORIGINAL
					//OOS.writeObject(array[j]+"\n"); //THIS IS MODIFIED
					//System.out.println(array[j]+"\n");// THIS IS ONE STEP FURTHER
				}	
		}
		} catch (Exception e) {
		}
	}
}